---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: myservicecanary
  namespace: yxeng
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myservice
  service:
    port: 9898
  analysis:
    alerts:
    - name: "on-call Slack"
      severity: info
      providerRef:
        name: alerts
        namespace: yxeng
    interval: 10s
    threshold: 5
    stepWeight: 10
    maxWeight: 100
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m


