apiVersion: flagger.app/v1beta1
kind: AlertProvider
metadata:
  name: alerts
  namespace: yxeng
spec:
  type: slack
  channel: alerts
  username: flagger
  address: {{ .Values.flagger.slackwebhook }}
